/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package it.cnr.istc.hsv.panels.test;

import it.cnr.istc.hsv.abstracts.extra.SensorTypeClassifier;
import it.cnr.istc.hsv.logic.entities.ESensor;
import it.cnr.istc.hsv.logic.entities.ESensorData;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;

/**
 *
 * @author Luca Coraci <luca.coraci@istc.cnr.it> ISTC-CNR
 */
public class SingleSensorTesterPanel_Numeric extends SensorTersterSupporter {

    /**
     * Creates new form SingleSensorTesterPanel
     */
    public SingleSensorTesterPanel_Numeric(ESensor sensor) {
        super(sensor);
        initComponents();
        this.init();
//        if(sensor.getSensorType().getName().equals(SensorTypeClassifier.SensorTypes.ENERGY.typeName())){
//            this.setBackground(Color.ORANGE);
//        }else if(sensor.getSensorType().getName().equals(SensorTypeClassifier.SensorTypes.LUMINOSITY.typeName())){
//            this.setBackground(Color.YELLOW);
//        }else if(sensor.getSensorType().getName().equals(SensorTypeClassifier.SensorTypes.PIR.typeName())){
//            this.setBackground(Color.GREEN);
//        }else if(sensor.getSensorType().getName().equals(SensorTypeClassifier.SensorTypes.POWER.typeName())){
//            this.setBackground(Color.WHITE);
//        }else if(sensor.getSensorType().getName().equals(SensorTypeClassifier.SensorTypes.TEMPERATURE.typeName())){
//            this.setBackground(Color.RED);
//        }else if(sensor.getSensorType().getName().equals(SensorTypeClassifier.SensorTypes.VOLTAGE.typeName())){
//            this.setBackground(Color.PINK);
//        }else if(sensor.getSensorType().getName().equals(SensorTypeClassifier.SensorTypes.GAP.typeName())){
//            this.setBackground(Color.BLUE);
//            this.jLabel1.setForeground(Color.WHITE);
//        }else{
//            this.setBackground(Color.CYAN);
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new JLabel();
        jButton1 = new JButton();
        jTextField1 = new JTextField();
        jCheckBox1 = new JCheckBox();

        jLabel1.setText("Sensor Name");

        jButton1.setText("Send");
        jButton1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jCheckBox1.setSelected(true);
        jCheckBox1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jCheckBox1)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1)
                    .addComponent(jButton1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)))
            .addComponent(jCheckBox1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ESensorData data = new ESensorData();
        data.setSensor(this.getSensor());
        data.setTimestamp(new Date());
        data.setUnit(this.getSensor().getSensorType().getLabelUnit());
        data.setValue(this.jTextField1.getText());
        this.trig(data);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if(jCheckBox1.isSelected()){
            this.show();
        }else{
            this.hide();
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    
    @Override
    public void setSensorNameLabel(String name) {
        this.jLabel1.setText(name);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton jButton1;
    private JCheckBox jCheckBox1;
    private JLabel jLabel1;
    private JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
