/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package it.cnr.istc.hsv.abstracts.extra.dummyreasoner;


import it.cnr.istc.hsv.abstracts.extra.DraggablePanel;
import java.beans.Beans;

/**
 *
 * @author Luca
 */
public class DisconnectedMessagePanel extends javax.swing.JPanel {

    private DraggablePanel draggablePanel;
    /**
     * Creates new form OutMessagePanel
     */
    public DisconnectedMessagePanel() {
        initComponents();
        if(!Beans.isDesignTime()){
//            jButton_close.setText(I18nTranslator.getInstance().translate(LangKeywords.OUTMESSAGE_CLOSE));
//            jLabel_labelSince.setText(I18nTranslator.getInstance().translate(LangKeywords.OUTMESSAGE_DOORCLOSEDAT));
//            jLabel_labelIn.setText(I18nTranslator.getInstance().translate(LangKeywords.OUTMESSAGE_IN));
//            jLabel_labelLastAct.setText(I18nTranslator.getInstance().translate(LangKeywords.OUTMESSAGE_LASTACT));
//            jLabel_mainText.setText(I18nTranslator.getInstance().translate(LangKeywords.OUTMESSAGE_MAINTEXT));
            
        }
    }
    
    public DisconnectedMessagePanel(DraggablePanel draggablePanel) {
        initComponents();
        this.draggablePanel =draggablePanel;
    }

    public void setDraggablePanel(DraggablePanel draggablePanel) {
        this.draggablePanel = draggablePanel;
    }
    
    public void setSince(String timestamp){
        this.jLabel_Since.setText(timestamp);
    }
    
//    public void setLastActivityTimeStamp(String timestamp){
//        this.jLabel_lastAct.setText(timestamp);
//    }
//    
//    public void setLastActivityIn(String where){
//        this.jLabel_lastActWhere.setText(where);
//    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_mainText = new javax.swing.JLabel();
        jLabel_labelSince = new javax.swing.JLabel();
        jLabel_Since = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton_close = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));

        jLabel_mainText.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_mainText.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_mainText.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_mainText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/cnr/istc/dvpis/images/HouseDisconnected32.png"))); // NOI18N
        jLabel_mainText.setText("<html>The house is <font color=red>disconnected</font>. Real time data collection is not working");

        jLabel_labelSince.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_labelSince.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_labelSince.setText("Since:");

        jLabel_Since.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Since.setForeground(new java.awt.Color(255, 255, 0));
        jLabel_Since.setText("loading..");

        jToolBar1.setBackground(new java.awt.Color(0, 0, 0));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setOpaque(false);

        jButton_close.setForeground(new java.awt.Color(255, 255, 255));
        jButton_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/cnr/istc/dvpis/images/delete16.png"))); // NOI18N
        jButton_close.setText("Close");
        jButton_close.setBorderPainted(false);
        jButton_close.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton_close.setIconTextGap(8);
        jButton_close.setOpaque(false);
        jButton_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_closeActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton_close);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel_mainText, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_labelSince)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Since, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_mainText, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Since)
                    .addComponent(jLabel_labelSince))
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_closeActionPerformed
        if(this.draggablePanel!=null){
            this.draggablePanel.setVisible(false);
        }
    }//GEN-LAST:event_jButton_closeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_close;
    private javax.swing.JLabel jLabel_Since;
    private javax.swing.JLabel jLabel_labelSince;
    private javax.swing.JLabel jLabel_mainText;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
